#############################################################################
# Makefile for building: message_queue
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Jul 8 13:04:43 2019
# Project:  message_queue.pro
# Template: app
# Command: /usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/qmake -spec /usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/qws/linux-arm-g++ -o Makefile message_queue.pro
#############################################################################

####### Compiler, tools and options

CC            = /home/troy/ATCI_lib/Toolchain/bin/arm-linux-gnueabihf-gcc
CXX           = /home/troy/ATCI_lib/Toolchain/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -march=armv7-a -marm -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a5 -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -march=armv7-a -marm -mthumb-interwork -mfloat-abi=hard -mfpu=neon -mtune=cortex-a5 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/qws/linux-arm-g++ -I. -I/usr/local/Trolltech/QtEmbedded-4.8.1-arm/include/QtCore -I/usr/local/Trolltech/QtEmbedded-4.8.1-arm/include/QtNetwork -I/usr/local/Trolltech/QtEmbedded-4.8.1-arm/include/QtGui -I/usr/local/Trolltech/QtEmbedded-4.8.1-arm/include -I. -I.
LINK          = /home/troy/ATCI_lib/Toolchain/bin/arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/QtEmbedded-4.7.1-arm/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEmbedded-4.8.1-arm/lib -lQtGui -L/usr/local/Trolltech/QtEmbedded-4.8.1-arm/lib -lQtNetwork -lQtCore -lrt -lpthread 
AR            = /home/troy/ATCI_lib/Toolchain/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = /home/troy/ATCI_lib/Toolchain/bin/arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		sem_com.cpp \
		MonitorFunction.cpp \
		M79.cpp \
		lldrv.cpp \
		taskM79.cpp \
		taskControl.cpp \
		taskAcquire.cpp \
		jiance_widget.cpp \
		inputdialog.cpp \
		RelayDelay.cpp moc_taskM79.cpp \
		moc_taskAcquire.cpp \
		moc_taskControl.cpp \
		moc_jiance_widget.cpp \
		moc_inputdialog.cpp \
		moc_RelayDelay.cpp
OBJECTS       = main.o \
		sem_com.o \
		MonitorFunction.o \
		M79.o \
		lldrv.o \
		taskM79.o \
		taskControl.o \
		taskAcquire.o \
		jiance_widget.o \
		inputdialog.o \
		RelayDelay.o \
		moc_taskM79.o \
		moc_taskAcquire.o \
		moc_taskControl.o \
		moc_jiance_widget.o \
		moc_inputdialog.o \
		moc_RelayDelay.o
DIST          = /usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/include_source_dir.prf \
		message_queue.pro
QMAKE_TARGET  = message_queue
DESTDIR       = 
TARGET        = message_queue

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_jiance_widget.h ui_inputdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: message_queue.pro  /usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/lib/libQtGui.prl \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/lib/libQtNetwork.prl \
		/usr/local/Trolltech/QtEmbedded-4.8.1-arm/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/qws/linux-arm-g++ -o Makefile message_queue.pro
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/release.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/lib/libQtGui.prl:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/lib/libQtNetwork.prl:
/usr/local/Trolltech/QtEmbedded-4.8.1-arm/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/QtEmbedded-4.8.1-arm/mkspecs/qws/linux-arm-g++ -o Makefile message_queue.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/message_queue1.0.0 || $(MKDIR) .tmp/message_queue1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/message_queue1.0.0/ && $(COPY_FILE) --parents sem_com.h MonitorFunction.h MonitorConfig.h M79.h lldrv.h HitHW.h Drv.h taskM79.h taskAcquire.h taskControl.h jiance_widget.h inputdialog.h RelayDelay.h .tmp/message_queue1.0.0/ && $(COPY_FILE) --parents main.cpp sem_com.cpp MonitorFunction.cpp M79.cpp lldrv.cpp taskM79.cpp taskControl.cpp taskAcquire.cpp jiance_widget.cpp inputdialog.cpp RelayDelay.cpp .tmp/message_queue1.0.0/ && $(COPY_FILE) --parents jiance_widget.ui inputdialog.ui .tmp/message_queue1.0.0/ && (cd `dirname .tmp/message_queue1.0.0` && $(TAR) message_queue1.0.0.tar message_queue1.0.0 && $(COMPRESS) message_queue1.0.0.tar) && $(MOVE) `dirname .tmp/message_queue1.0.0`/message_queue1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/message_queue1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_taskM79.cpp moc_taskAcquire.cpp moc_taskControl.cpp moc_jiance_widget.cpp moc_inputdialog.cpp moc_RelayDelay.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_taskM79.cpp moc_taskAcquire.cpp moc_taskControl.cpp moc_jiance_widget.cpp moc_inputdialog.cpp moc_RelayDelay.cpp
moc_taskM79.cpp: Drv.h \
		M79.h \
		HitHW.h \
		taskM79.h
	/usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/moc $(DEFINES) $(INCPATH) taskM79.h -o moc_taskM79.cpp

moc_taskAcquire.cpp: jiance_widget.h \
		directoryviewer.h \
		Drv.h \
		M79.h \
		HitHW.h \
		inputdialog.h \
		taskAcquire.h
	/usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/moc $(DEFINES) $(INCPATH) taskAcquire.h -o moc_taskAcquire.cpp

moc_taskControl.cpp: RelayDelay.h \
		taskControl.h
	/usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/moc $(DEFINES) $(INCPATH) taskControl.h -o moc_taskControl.cpp

moc_jiance_widget.cpp: directoryviewer.h \
		Drv.h \
		M79.h \
		HitHW.h \
		inputdialog.h \
		jiance_widget.h
	/usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/moc $(DEFINES) $(INCPATH) jiance_widget.h -o moc_jiance_widget.cpp

moc_inputdialog.cpp: inputdialog.h
	/usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/moc $(DEFINES) $(INCPATH) inputdialog.h -o moc_inputdialog.cpp

moc_RelayDelay.cpp: RelayDelay.h
	/usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/moc $(DEFINES) $(INCPATH) RelayDelay.h -o moc_RelayDelay.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_jiance_widget.h ui_inputdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_jiance_widget.h ui_inputdialog.h
ui_jiance_widget.h: jiance_widget.ui
	/usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/uic jiance_widget.ui -o ui_jiance_widget.h

ui_inputdialog.h: inputdialog.ui
	/usr/local/Trolltech/QtEmbedded-4.8.1-arm/bin/uic inputdialog.ui -o ui_inputdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp Drv.h \
		M79.h \
		HitHW.h \
		lldrv.h \
		start_Monitor.h \
		jiance_widget.h \
		directoryviewer.h \
		inputdialog.h \
		taskAcquire.h \
		taskControl.h \
		RelayDelay.h \
		taskM79.h \
		MonitorConfig.h \
		sem_com.h \
		/usr/include/linux/mtio.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

sem_com.o: sem_com.cpp sem_com.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sem_com.o sem_com.cpp

MonitorFunction.o: MonitorFunction.cpp MonitorFunction.h \
		Drv.h \
		M79.h \
		HitHW.h \
		lldrv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MonitorFunction.o MonitorFunction.cpp

M79.o: M79.cpp M79.h \
		HitHW.h \
		lldrv.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o M79.o M79.cpp

lldrv.o: lldrv.cpp lldrv.h \
		Drv.h \
		M79.h \
		HitHW.h \
		at91_gpio.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lldrv.o lldrv.cpp

taskM79.o: taskM79.cpp taskM79.h \
		Drv.h \
		M79.h \
		HitHW.h \
		sem_com.h \
		taskAcquire.h \
		jiance_widget.h \
		directoryviewer.h \
		inputdialog.h \
		MonitorFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskM79.o taskM79.cpp

taskControl.o: taskControl.cpp taskControl.h \
		RelayDelay.h \
		Drv.h \
		M79.h \
		HitHW.h \
		MonitorFunction.h \
		sem_com.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskControl.o taskControl.cpp

taskAcquire.o: taskAcquire.cpp taskAcquire.h \
		jiance_widget.h \
		directoryviewer.h \
		Drv.h \
		M79.h \
		HitHW.h \
		inputdialog.h \
		lldrv.h \
		MonitorFunction.h \
		sem_com.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskAcquire.o taskAcquire.cpp

jiance_widget.o: jiance_widget.cpp jiance_widget.h \
		directoryviewer.h \
		Drv.h \
		M79.h \
		HitHW.h \
		inputdialog.h \
		ui_jiance_widget.h \
		MonitorConfig.h \
		MonitorFunction.h \
		sem_com.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o jiance_widget.o jiance_widget.cpp

inputdialog.o: inputdialog.cpp inputdialog.h \
		ui_inputdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputdialog.o inputdialog.cpp

RelayDelay.o: RelayDelay.cpp RelayDelay.h \
		Drv.h \
		M79.h \
		HitHW.h \
		MonitorFunction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RelayDelay.o RelayDelay.cpp

moc_taskM79.o: moc_taskM79.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskM79.o moc_taskM79.cpp

moc_taskAcquire.o: moc_taskAcquire.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskAcquire.o moc_taskAcquire.cpp

moc_taskControl.o: moc_taskControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taskControl.o moc_taskControl.cpp

moc_jiance_widget.o: moc_jiance_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_jiance_widget.o moc_jiance_widget.cpp

moc_inputdialog.o: moc_inputdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputdialog.o moc_inputdialog.cpp

moc_RelayDelay.o: moc_RelayDelay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_RelayDelay.o moc_RelayDelay.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

